"""portfolio table fix

Revision ID: 1f628e777676
Revises: c97a27dac14b
Create Date: 2024-11-04 20:08:43.912189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f628e777676'
down_revision: Union[str, None] = 'c97a27dac14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_portfolios', sa.Column('price', sa.DECIMAL(precision=20, scale=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_portfolios', 'price')
    # ### end Alembic commands ###
