"""refresh_tokens table init

Revision ID: 3de886c1a49f
Revises: 9f4d0019b615
Create Date: 2024-12-09 00:55:52.852451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de886c1a49f'
down_revision: Union[str, None] = '9f4d0019b615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('refresh_token', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'refresh_tokens', ['refresh_token'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'refresh_token')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
