"""help table update

Revision ID: f7afefb69118
Revises: 85f4de362d21
Create Date: 2024-11-15 22:27:02.765127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7afefb69118'
down_revision: Union[str, None] = '85f4de362d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_messages', sa.Column('add_time', sa.TIMESTAMP(), nullable=False))
    op.drop_column('help_messages', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_messages', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('help_messages', 'add_time')
    # ### end Alembic commands ###
